spring:
  application:
    name: springcloud-service-admin
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: dev
server:
  port: 8763

---
spring:
  profiles: prod
server:
  port: 8762
