spring:
  application:
    name: springcloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
feign:
  hystrix:
    enabled: true
---
spring:
  profiles: dev
server:
  port: 8765
---
spring:
  profiles: prod
server:
  port: 8766


