spring:
  application:
    name: springcloud-zuul
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: SPRINGCLOUD-WEB-ADMIN-RIBBON
    api-b:
      path: /api/b/**
      serviceId: SPRINGCLOUD-WEB-ADMIN-FEIGN
---
spring:
  profiles: dev
---
spring:
  profiles: prod
